Update to ACRA 4.5
Fixes crash:
java.lang.RuntimeException: Unable to create service com.ianhanniballake.contractiontimer.notification.NotificationUpdateService: java.lang.RuntimeException: Unable to create application com.ianhanniballake.contractiontimer.ContractionTimerApplication: java.lang.IllegalStateException: ACRA#init called more than once
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2283)
        at android.app.ActivityThread.access$1600(ActivityThread.java:127)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4441)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Unable to create application com.ianhanniballake.contractiontimer.ContractionTimerApplication: java.lang.IllegalStateException: ACRA#init called more than once
        at android.app.LoadedApk.makeApplication(LoadedApk.java:495)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2269)
        ... 10 more
Caused by: java.lang.IllegalStateException: ACRA#init called more than once
        at org.acra.ACRA.init(SourceFile:121)
        at com.ianhanniballake.contractiontimer.ContractionTimerApplication.onCreate(SourceFile:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:492)
        ... 11 more
java.lang.RuntimeException: Unable to create application com.ianhanniballake.contractiontimer.ContractionTimerApplication: java.lang.IllegalStateException: ACRA#init called more than once
        at android.app.LoadedApk.makeApplication(LoadedApk.java:495)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2269)
        at android.app.ActivityThread.access$1600(ActivityThread.java:127)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4441)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: ACRA#init called more than once
        at org.acra.ACRA.init(SourceFile:121)
        at com.ianhanniballake.contractiontimer.ContractionTimerApplication.onCreate(SourceFile:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:492)
        ... 11 more
java.lang.IllegalStateException: ACRA#init called more than once
        at org.acra.ACRA.init(SourceFile:121)
        at com.ianhanniballake.contractiontimer.ContractionTimerApplication.onCreate(SourceFile:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:492)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2269)
        at android.app.ActivityThread.access$1600(ActivityThread.java:127)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4441)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)